### ISSUE TITLE
Would you please add LICENSE

### ISSUE THREAD

**Issue by hitsuji-no-shippo** [jsmrcaga/action-netlify-deploy#1]
Hi @jsmrcaga .

I am an English learner. Sorry if the sentence is hard to understand.

I would like to change the code of this action and distribute. The main change is changing npm to yarn. However, copyright and LICENSE are not written, would you please add them?

**Comment by jsmrcaga** [comment]
I'm adding a reminder to do it tonight or tomorrow morning ;) 

I did not expect this repo to get attention to be honest
