### ISSUE TITLE
Action should fail if build script fails

### ISSUE THREAD

**Issue by tpluscode** [jsmrcaga/action-netlify-deploy#24]
It came a surprise to me that while node 17 broke some of my builds (re #23), the GH workflows did not actually fail. 
So now I have half-deployed websites 😬 

Not sure if it's something about my code, but if not, I'd expect a failed build to actually break the workflow

**Comment by tpluscode** [comment]
Here's one example: https://github.com/hypermedia-app/shaperone/runs/4140456096?check_suite_focus=true#step:9:209

It fails and then proceeds with Netlify push

**Comment by jsmrcaga** [comment]
Hey @tpluscode ! thanks a lot for your issue, you're absolutely right.
I'm not an expert on bash scripts, but I'm guessing we are missing this (a `set -e` at the start):
https://stackoverflow.com/a/19622300/1895443

it would break fail the script if an error occurs. I'll make a PR this evening (in 2/3 hours)
