### ISSUE TITLE
Build fails because of nvm while it's optional

### ISSUE THREAD

**Issue by ajbura** [jsmrcaga/action-netlify-deploy#27]
https://github.com/ajbura/cinny/runs/4248572369?check_suite_focus=true

Since latest commit in your branch my builds are failing because I do not use .nvm.

**Comment by jsmrcaga** [comment]
Hey @ajbura , while we fix this I would advice you to add a sha or specific version on your workflow.
Thanks for the issue we will take a look at this asap!

**Comment by codler** [comment]
Can you update the readme?

**Comment by lucianojung** [comment]
Hi I have the same problem using master and v.1.7.1. Which version is working?

**Comment by jsmrcaga** [comment]
@codler @lucianojung @ajbura 
Sorry this took so long.

I've openend a Pull request (linked to this issue). You can review it if you have the time to check if it matches your use cases
