### ISSUE TITLE
NETLIFY_DEPLOY_TO_PROD is required but returns a warning

### ISSUE THREAD

**Issue by sazzer** [jsmrcaga/action-netlify-deploy#3]
If I want to use this to deploy a site and make it live, I need to add:
```
          NETLIFY_DEPLOY_TO_PROD: true
```
to the step. That's great.

However, if I do that then I get this warning at the start of the step running:
```
##[warning]Unexpected input 'NETLIFY_DEPLOY_TO_PROD', valid inputs are ['entryPoint', 'args', 'NETLIFY_AUTH_TOKEN', 'NETLIFY_SITE_ID', 'NETLIFY_DEPLOY_MESSAGE', 'build_directory', 'functions_directory']
```

It works correctly, but just gives that output. Without the setting it no longer warns but it also doesn't deploy to production.

**Comment by jsmrcaga** [comment]
Thanks for the issue.
As a matter of fact the Input was missing from the input declarations.

Should be fixed with https://github.com/jsmrcaga/action-netlify-deploy/pull/4
