### ISSUE TITLE
Option to skip nvm

### ISSUE THREAD

**Issue by penx** [jsmrcaga/action-netlify-deploy#31]
Thanks for building this action!

At the point I run action-netlify-deploy, my application has already been installed and built, and I have the version of node that I need.

I _do_ have an `.nvmrc` file though, so this step I think will still install nvm, even though I don't need it.

https://github.com/jsmrcaga/action-netlify-deploy/commit/fb6a5f936a4b06a8f7793e69fc5a022ffe39807a

Would it be possible to have an option to skip nvm rather than detecting it? 🙏

**Comment by jsmrcaga** [comment]
Hi there @penx !

I had some time this evening and opened a simple pull request here
https://github.com/jsmrcaga/action-netlify-deploy/pull/33
if it's okay with you, can I let you review/approve. I'll then release a new version and hopefully you'll be good!

**Comment by jsmrcaga** [comment]
@penx  I've released version 1.8.0, if it works for you (using `use_nvm: false`) I'll let you close this issue! Thanks!

**Comment by penx** [comment]
great, thanks, may not get a chance to test this until September but I've looked at the code and pretty certain it will work, thanks!
