### ISSUE TITLE
sh: 1: netlify: not found

### ISSUE THREAD

**Issue by tpluscode** [jsmrcaga/action-netlify-deploy#59]
Just got that message from the action: https://github.com/openlayers-elements/openlayers-elements/actions/runs/11324294370/job/31488803794#step:5:146

Something changed upstream?

**Comment by happylolonly** [comment]
Merge please

**Comment by jsmrcaga** [comment]
It looks like the latest Ubuntu image on the runners no longer has `netlify` installed

It was present on the 22 Ubuntu image
https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md

The Ubuntu 24 however does not list Netlify

https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md

Your PR https://github.com/jsmrcaga/action-netlify-deploy/pull/60 covers this @tpluscode thanks a lot!
In any case users can (and should) fix this by not using` ubuntu-latest` but by specifying the version they want in their own workflows ([example from your error](https://github.com/openlayers-elements/openlayers-elements/actions/runs/11324294370/workflow#L7))

Published https://github.com/jsmrcaga/action-netlify-deploy/releases/tag/v2.3.0 so you can update your workflows too

**Comment by tpluscode** [comment]
Thanks for the details. I'm actually surprised that ubuntu came with Netlify in the first place

**Comment by jsmrcaga** [comment]
Yeah it was the image prepared by GitHub. Had a fun case today migrating something between GHActions and CircleCI cause they had different default binaries
